### ISSUE TITLE
Loading of clean-css-brunch failed due to Cannot find module 'amdefine'

### ISSUE THREAD

**Issue by bigp** [brunch/clean-css-brunch#15]
Getting this error (here's the output with `LOGGY_STACKS=true`):

```
17 Jun 19:20:16 - warn: Loading of clean-css-brunch failed due to Cannot find module 'amdefine'
  at Function.Module._resolveFilename (module.js:325:15)
  at Function.Module._load (module.js:276:25)
  at Module.require (module.js:353:17)
  at require (internal/module.js:12:17)
  at Object.<anonymous> (MY_PROJECT_PATH\brunch\node_modules\clean-cs
s-brunch\node_modules\clean-css\node_modules\source-map\lib\source-map\source-map-generator.js:8:18)

  at Module._compile (module.js:409:26)
  at Object.Module._extensions..js (module.js:416:10)
  at Module.load (%APPDATA%\Roaming\npm\node_modules\brunch\node_modules\coffee-s
cript\lib\coffee-script\register.js:45:36)
  at Function.Module._load (module.js:300:12)
  at Module.require (module.js:353:17)
  at require (internal/module.js:12:17)
  at Object.<anonymous> (MY_PROJECT_PATH\brunch\node_modules\clean-cs
s-brunch\node_modules\clean-css\node_modules\source-map\lib\source-map.js:6:30)
  at Module._compile (module.js:409:26)
  at Object.Module._extensions..js (module.js:416:10)
  at Module.load (%APPDATA%\Roaming\npm\node_modules\brunch\node_modules\coffee-s
cript\lib\coffee-script\register.js:45:36)
  at Function.Module._load (module.js:300:12)
  at Module.require (module.js:353:17)
  at require (internal/module.js:12:17)
  at Object.<anonymous> (MY_PROJECT_PATH\brunch\node_modules\clean-cs
s-brunch\node_modules\clean-css\lib\stringifier\source-maps.js:1:88)
  at Module._compile (module.js:409:26)
  at Object.Module._extensions..js (module.js:416:10)
  at Module.load (%APPDATA%\Roaming\npm\node_modules\brunch\node_modules\coffee-s
cript\lib\coffee-script\register.js:45:36)
  at Function.Module._load (module.js:300:12)
  at Module.require (module.js:353:17)
  at require (internal/module.js:12:17)
  at Object.<anonymous> (MY_PROJECT_PATH\brunch\node_modules\clean-cs
s-brunch\node_modules\clean-css\lib\clean.js:16:26)
  at Module._compile (module.js:409:26)
  at Object.Module._extensions..js (module.js:416:10)
  at Module.load (%APPDATA%\Roaming\npm\node_modules\brunch\node_modules\coffee-s
cript\lib\coffee-script\register.js:45:36)
  at Function.Module._load (module.js:300:12)
  at Module.require (module.js:353:17)
  at require (internal/module.js:12:17)
  at Object.<anonymous> (MY_PROJECT_PATH\brunch\node_modules\clean-cs
s-brunch\node_modules\clean-css\index.js:1:80)
  at Module._compile (module.js:409:26)
  at Object.Module._extensions..js (module.js:416:10)
  at Module.load (%APPDATA%\Roaming\npm\node_modules\brunch\node_modules\coffee-s
cript\lib\coffee-script\register.js:45:36)
  at Function.Module._load (module.js:300:12)
  at Module.require (module.js:353:17)
  at require (internal/module.js:12:17)
  at Object.<anonymous> (MY_PROJECT_PATH\brunch\node_modules\clean-cs
s-brunch\index.js:3:18)
  at Module._compile (module.js:409:26)
  at Object.Module._extensions..js (module.js:416:10)
  at Module.load (%APPDATA%\Roaming\npm\node_modules\brunch\node_modules\coffee-s
cript\lib\coffee-script\register.js:45:36)
  at Function.Module._load (module.js:300:12)
  at Module.require (module.js:353:17)
  at require (internal/module.js:12:17)
  at packages.filter.plugins.map.plugin.filter.requireModule (%APPDATA%\Roaming\n
pm\node_modules\brunch\lib\plugins.js:44:18)
  at %APPDATA%\Roaming\npm\node_modules\brunch\lib\plugins.js:73:18
  at Array.map (native)
  at prop.filter.dependency.map (%APPDATA%\Roaming\npm\node_modules\brunch\lib\pl
ugins.js:69:8)
  at %APPDATA%\Roaming\npm\node_modules\brunch\lib\plugins.js:110:12
  at Array.map (native)
  at packages.filter.plugins.map.plugin.filter.prop.filter.slice.call.map.uniqueDeps.map.reduce (C:\
Users\Chamberlain\AppData\Roaming\npm\node_modules\brunch\lib\plugins.js:109:5)
  at Object.packages.filter.plugins.map.plugin.filter.prop.filter.slice.call.map.uniqueDeps.map.expo
rts.init.plugins.filter.map.preCompilers.push.teardownBrunch [as init] (%APPDATA%
\Roaming\npm\node_modules\brunch\lib\plugins.js:129:20)
  at %APPDATA%\Roaming\npm\node_modules\brunch\lib\watch.js:116:19

17 Jun 19:20:16 - error: Initialization error -  Cannot read property 'brunchPluginName' of null
Type  at %APPDATA%\Roaming\npm\node_modules\brunch\lib\plugins.js:130:33
  at Array.filter (native)
  at Object.packages.filter.plugins.map.plugin.filter.prop.filter.slice.call.map.uniqueDeps.map.expo
rts.init.plugins.filter.map.preCompilers.push.teardownBrunch [as init] (%APPDATA%
\Roaming\npm\node_modules\brunch\lib\plugins.js:129:38)
  at %APPDATA%\Roaming\npm\node_modules\brunch\lib\watch.js:116:19
```

**Comment by denysdovhan** [comment]
Hi @bigp! Could you give us more detailed explanation of your problem?

P.S: Are you sure you've installed all of your dependencies properly?

**Comment by bigp** [comment]
Ah right, I've completely forgotten about this issue! Don't worry about it though, I've moved on since. :)

**Comment by denysdovhan** [comment]
@bigp but, nevertheless, can you describe your issue. Maybe problem still exists and it's needed to be fixed.
